version: 2.1
orbs:
  node: circleci/node@3.0.0
jobs:
  build:
    docker:
      - image: circleci/node:14.17.5
        auth:
          username: mydockerhub-user
          password: $DOCKERHUB_PASSWORD # context / project UI env-var reference
    steps:
      - run: node --version
      - checkout
      - run: yarn
      - run: export DATO_API_TOKEN=$TDA_DATO_API_TOKEN; yarn build
      - run: ssh -p 7171 -o StrictHostKeyChecking=no -o UserKnownHostsFile=/dev/null unfold@vs.li-ma.nl "mkdir -p tda"
      - run: scp -r -P 7171 -o StrictHostKeyChecking=no -o UserKnownHostsFile=/dev/null ./public/* unfold@vs.li-ma.nl:tda/
      - run:
          name: Notify DatoCMS about the status of the job
          command: 'curl -X POST --data-binary "{\"payload\": { \"branch\": \"$CIRCLE_BRANCH\", \"status\": \"failed\" } }" https://webhooks.datocms.com/b430ae8ebb/deploy-results'
          when: on_fail
      - run:
          name: Notify DatoCMS about the status of the job
          command: 'curl -X POST --data-binary "{\"payload\": { \"branch\": \"$CIRCLE_BRANCH\", \"status\": \"success\" } }" https://webhooks.datocms.com/b430ae8ebb/deploy-results'
          when: on_success
    
workflows:
  build:
    jobs:
      - build
