version: 2.1
orbs:
  node: circleci/node@3.0.0
jobs:
  install-node-example:
    docker:
      - image: circleci/node:14.0.0
        auth:
          username: mydockerhub-user
          password: $DOCKERHUB_PASSWORD  # context / project UI env-var reference
    steps:
      - checkout
      - node/install:
          install-yarn: true
      - run: node --version
workflows:
  test_my_app:
    jobs:
      - install-node-example

