version: 2.1
orbs:
  node: circleci/node@3.0.0
jobs:
  install-and-deploy:
    docker:
      - image: circleci/node:14.0.0
        auth:
          username: mydockerhub-user
          password: $DOCKERHUB_PASSWORD  # context / project UI env-var reference
    steps:
      - run: node --version
      - checkout
      - run: yarn
      - run: yarn build
      - run: scp -r -P 7171 -o StrictHostKeyChecking=no -o UserKnownHostsFile=/dev/null ./public/* unfold@vs.li-ma.nl:site/
      - run:
          name: Notify DatoCMS about the status of the job
          command: 'curl -X POST --data-binary "{\"payload\": { \"branch\": \"$CIRCLE_BRANCH\", \"status\": \"failed\" } }" https://webhooks.datocms.com/jdxmJLwZBk/deploy-results'
          when: on_fail
      - run:
          name: Notify DatoCMS about the status of the job
          command: 'curl -X POST --data-binary "{\"payload\": { \"branch\": \"$CIRCLE_BRANCH\", \"status\": \"success\" } }" https://webhooks.datocms.com/jdxmJLwZBk/deploy-results'
          when: on_success
  
workflows:
  test_my_app:
    jobs:
      - install-and-deploy

